# this is the base unpinned environment for ``stenv``; to manually resolve an environment from this file, run the following: 
# conda env create -n stenv -f https://raw.githubusercontent.com/spacetelescope/stenv/main/environment.yaml 

channels:
  - conda-forge

dependencies:
  - fitsverify
  - hstcal>=3.0.3
  - python>=3.10
  # TODO uncomment this after next release of Mamba (2.4.1)
  # - uv
  - pip:
      - astropy
      - acstools
      - asdf
      - calcos
      - ccdproc
      - costools
      - crds
      - dask
      - drizzlepac
      - ginga
      - h5py
      - ipython
      - jupyter
      - jwst
      - nictools
      - numpy
      - reftools
      - romancal
      - scipy
      - stcal
      - stdatamodels
      - stistools
      - stsynphot
      - stregion
      - synphot
      - wfc3tools
      - wfpc2tools
