channels:
    - conda-forge
dependencies:
    - graphviz
    - pip
    - python=3.13
    - pip:
        - dunamai
        - numpy
        - numpydoc
        - scipy
        - sphinx
        - sphinx-inline-tabs
        - sphinx-rtd-theme
