name: build

on:
  push:
    paths:
      - "**/*.yml"
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}

env:
  PYSYN_CDBS: /home/runner/trds
  CRDS_PATH: /home/runner/crds_cache
  CRDS_SERVER_URL: https://hst-crds.stsci.edu

jobs:
  build:
    name: build environment (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.9' ]
    steps:
      - uses: actions/checkout@main
      - run: sed -i "s/python==3.9/python==${{ matrix.python }}.*/g" spacetelescope-env-latest.yml
      - uses: mtkennerly/dunamai-action@master
        id: version
      - run: echo "::set-output name=date::$(date +'%Y%m%d')"
        id: date
      - uses: actions/cache@main
        id: cache
        with:
          path: |
            /home/runner/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-${{ matrix.python }}-latest
          key: conda-${{ runner.os }}-${{ matrix.python }}-${{ steps.date.outputs.date }}
      - uses: conda-incubator/setup-miniconda@main
        with:
          activate-environment: spacetelescope-env-${{ matrix.python }}-latest
          environment-file: spacetelescope-env-latest.yml
          python-version: ${{ matrix.python }}.*
          auto-update-conda: true
          use-only-tar-bz2: true
      - run: conda update --all
        if: steps.cache.outputs.cache-hit != 'true'
      - run: conda env export > spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
      - run: sed -i "s/spacetelescope-env-${{ matrix.python }}-latest/spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}/g" spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
      - run: cat spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
      - uses: actions/upload-artifact@main
        with:
          name: spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
  run_packaged_unit_tests:
    name: run `${{ matrix.package }}` unit tests (Python ${{ matrix.python }})
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [ acstools, ccdproc, costools, reftools, stsynphot, synphot, wfpc2tools ]
        python: [ '3.9' ]
        include:
          - package: acstools
            dependencies: [ ci-watson, pytest-astropy-header, pytest-remotedata ]
          - package: ccdproc
            dependencies: [ memory_profiler, pytest-astropy ]
          - package: costools
            dependencies: [ ]
          #- package: crds
          #  dependencies: [ lockfile, mock, nose, pylint ]
          #- package: nictools
          #  dependencies: [ ]
          #- package: pysynphot
          #  dependencies: [ pytest-remotedata, pytest-astropy-header ]
          - package: reftools
            dependencies: [ pytest-remotedata, pytest-astropy-header ]
          - package: stsynphot
            dependencies: [ ci-watson, pytest-astropy ]
          - package: synphot
            dependencies: [ pytest-astropy ]
          #- package: wfc3tools
          #  dependencies: [ ]
          - package: wfpc2tools
            dependencies: [ ]
    steps:
      - uses: actions/checkout@main
      - run: sed -i "s/python==3.9/python==${{ matrix.python }}.*/g" spacetelescope-env-latest.yml
      - run: echo "::set-output name=date::$(date +'%Y%m%d')"
        id: date
      - uses: actions/cache@main
        with:
          path: |
            /home/runner/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-${{ matrix.python }}-latest
          key: conda-${{ runner.os }}-${{ matrix.python }}-${{ steps.date.outputs.date }}
      - uses: conda-incubator/setup-miniconda@main
        with:
          activate-environment: spacetelescope-env-${{ matrix.python }}-latest
          environment-file: spacetelescope-env-latest.yml
          python-version: ${{ matrix.python }}.*
          auto-update-conda: true
          use-only-tar-bz2: true
      - run: pip install pytest-xdist ${{ join(matrix.dependencies, ' ') }}
      - run: pytest -n auto --pyargs ${{ matrix.package }}
  run_repository_unit_tests:
    name: run `${{ matrix.package }}` unit tests (Python ${{ matrix.python }})
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [ calcos, hstcal ]
        python: [ '3.9' ]
        include:
          - package: calcos
            repository: spacetelescope/calcos
            dependencies: [ ci_watson ]
            test_directory: tests
          #- package: drizzlepac
          #  repository: spacetelescope/drizzlepac
          #  dependencies: [ ci-watson, crds, pytest-remotedata ]
          #  test_directory: tests
          - package: hstcal
            repository: spacetelescope/hstcal
            dependencies: [ ci-watson ]
            test_directory: tests
          #- package: stistools
          #  repository: spacetelescope/stistools
          #  dependencies: [ six ]
          #  test_directory: tests
    steps:
      - uses: actions/checkout@main
        with:
          path: spacetelescope-env-distribution
      - run: sed -i "s/python==3.9/python==${{ matrix.python }}.*/g" spacetelescope-env-distribution/spacetelescope-env-latest.yml
      - run: echo "::set-output name=date::$(date +'%Y%m%d')"
        id: date
      - uses: actions/cache@main
        with:
          path: |
            /home/runner/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-${{ matrix.python }}-latest
          key: conda-${{ runner.os }}-${{ matrix.python }}-${{ steps.date.outputs.date }}
      - uses: conda-incubator/setup-miniconda@main
        with:
          activate-environment: spacetelescope-env-${{ matrix.python }}-latest
          environment-file: spacetelescope-env-distribution/spacetelescope-env-latest.yml
          python-version: ${{ matrix.python }}.*
          auto-update-conda: true
          use-only-tar-bz2: true
      - uses: actions/checkout@main
        with:
          path: ${{ matrix.package }}
          repository: ${{ matrix.repository }}
      - run: cd ${{ matrix.package }} && pip install pytest-xdist ${{ join(matrix.dependencies, ' ') }}
      - run: cd ${{ matrix.package }} && pytest -n auto ${{ matrix.test_directory }}
  run_calcos_smoke_tests:
    name: run `calcos` smoke tests (Python ${{ matrix.python }})
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.9' ]
    steps:
      - uses: actions/checkout@main
        with:
          lfs: true
      - run: sed -i "s/python==3.9/python==${{ matrix.python }}.*/g" spacetelescope-env-latest.yml
      - run: echo "::set-output name=date::$(date +'%Y%m%d')"
        id: date
      - uses: actions/cache@main
        with:
          path: |
            /home/runner/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-${{ matrix.python }}-latest
          key: conda-${{ runner.os }}-${{ matrix.python }}-${{ steps.date.outputs.date }}
      - uses: conda-incubator/setup-miniconda@main
        with:
          activate-environment: spacetelescope-env-${{ matrix.python }}-latest
          environment-file: spacetelescope-env-latest.yml
          python-version: ${{ matrix.python }}.*
          auto-update-conda: true
          use-only-tar-bz2: true
      - uses: actions/cache@main
        with:
          path: 'tests/data/'
          key: conda-${{ hashFiles('tests/data/*') }}
      - run: calcos la8n01qkq_rawtag_a.fits
        env:
          jref: /home/runner/crds_cache/hst/references/hst/
  export:
    name: export environment
    needs: [ run_packaged_unit_tests, run_repository_unit_tests, run_calcos_smoke_tests ]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [ '3.9' ]
    steps:
      - uses: actions/checkout@main
      - uses: mtkennerly/dunamai-action@master
        id: version
      - uses: dawidd6/action-download-artifact@master
        with:
          name: spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
      - uses: svenstaro/upload-release-action@master
        with:
          file: spacetelescope-env-${{ matrix.python }}-${{ steps.version.outputs.version }}.yml
